### ISSUE TITLE
ffjson panic in my project

### ISSUE THREAD

**Issue by oiooj** [pquerna/ffjson#198]
```
unexpected fault address 0x7f311054c035
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f311054c035 pc=0x6452d1]

goroutine 932 [running]:
runtime.throw(0x84ef50, 0x5)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420581398 sp=0xc420581378
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc4205813f0 sp=0xc420581398
github.com/pquerna/ffjson/fflib/v1.(*ffReader).ReadByteNoWS(0xc42f008210, 0x5b, 0x0, 0xc420581468)
        /data/golang/src/github.com/pquerna/ffjson/fflib/v1/reader.go:82 +0x31 fp=0xc4205813f8 sp=0xc4205813f0
github.com/pquerna/ffjson/fflib/v1.(*FFLexer).scanReadByte(0xc420080280, 0x5b, 0x0, 0x0)
        /data/golang/src/github.com/pquerna/ffjson/fflib/v1/lexer.go:162 +0x10f fp=0xc420581438 sp=0xc4205813f8
github.com/pquerna/ffjson/fflib/v1.(*FFLexer).Scan(0xc420080280, 0x0)
        /data/golang/src/github.com/pquerna/ffjson/fflib/v1/lexer.go:403 +0x43 fp=0xc420581478 sp=0xc420581438

```

**Comment by erikdubbelboer** [comment]
To find what is causing this you would have to provide the input JSON and structure you are trying to unmarshal it into. Just a stacktrace isn't really helpful.
